# docker-compose.yml
version: "3"
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    environment:
        - MONGO_INITDB_DATABASE=admin
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=helloworld
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/databases/dev.archive
      - ./database/production:/databases/production